#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    echo "please use: sudo ./bin/install.sh"
    exit 1
fi

apt install busybox udhcpc
cp ec20.service /usr/lib/systemd/system/ec20.service
sudo systemctl daemon-reload
sudo systemctl enable ec20

